from miticos import miticos
celebi=miticos("Celebi","Psiquico",50,60,20,"Scratch","Magical Leaf","Ancient Power","Confusion",50,0,10)
celebi.atacar()
celebi.mostrar_vida_pokemon()
celebi.rec_vida()
print("-"*30)
celebi.mostrar_vida_pokemon()
celebi.mostrar_atributos()
celebi.muda_golpe()
celebi.atacar()
celebi.defender()
